//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anmat.Server.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anmat.Server.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor {0} no puede ser convertido al tipo {1} definido en la metadata  del documento {2}..
        /// </summary>
        internal static string CsvDocumentReader_CantConvertFieldValue {
            get {
                return ResourceManager.GetString("CsvDocumentReader_CantConvertFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna {0} no esta definida en la metadata del documento {1}..
        /// </summary>
        internal static string CsvDocumentReader_ColumnNotDefined {
            get {
                return ResourceManager.GetString("CsvDocumentReader_ColumnNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se esperaban {0} columnas separadas por &apos;;&apos;. Se encontraron {1} en la linea {2} del documento {3}..
        /// </summary>
        internal static string CsvDocumentReader_ExpectedColumnsFailed {
            get {
                return ResourceManager.GetString("CsvDocumentReader_ExpectedColumnsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no tiene el formato esperado. Se esperaba un {1} valido en el documento {2}..
        /// </summary>
        internal static string CsvDocumentReader_InvalidFieldFormat {
            get {
                return ResourceManager.GetString("CsvDocumentReader_InvalidFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} del documento {1} tiene valor nulo en la linea {2} y la metadata de la columna esta definida como no Nullable..
        /// </summary>
        internal static string CsvDocumentReader_NullValueOnFieldNotAllowed {
            get {
                return ResourceManager.GetString("CsvDocumentReader_NullValueOnFieldNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El job {0} para la version {1} ha finalizado exitosamente.
        /// </summary>
        internal static string DataGenerationJobService_JobCompleted {
            get {
                return ResourceManager.GetString("DataGenerationJobService_JobCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado metadata definida para generar el documento {0}.
        /// </summary>
        internal static string DocumentGenerator_NoMetadataFound {
            get {
                return ResourceManager.GetString("DocumentGenerator_NoMetadataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo {0} no existe.
        /// </summary>
        internal static string DocumentReader_FileNotExists {
            get {
                return ResourceManager.GetString("DocumentReader_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La extension de archivo {0} no esta soportada. Extension esperada: {1}.
        /// </summary>
        internal static string DocumentReader_NotSupportedFileExtension {
            get {
                return ResourceManager.GetString("DocumentReader_NotSupportedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El job con id {0} y version {1} no se encuentra en progreso, por lo tanto no puede realizarse ningun procesamiento de informacion.
        /// </summary>
        internal static string LatestJob_NotInProgress {
            get {
                return ResourceManager.GetString("LatestJob_NotInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningun job creado,  por lo tanto no puede realizarse ningun procesamiento de informacion.
        /// </summary>
        internal static string LatestJob_Null {
            get {
                return ResourceManager.GetString("LatestJob_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al crear la entidad {0}.
        /// </summary>
        internal static string MongoRepository_CreateError {
            get {
                return ResourceManager.GetString("MongoRepository_CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al inicializar la base de datos {0}.
        /// </summary>
        internal static string MongoRepository_DatabaseCreationError {
            get {
                return ResourceManager.GetString("MongoRepository_DatabaseCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al eliminar todas las entidades {0}.
        /// </summary>
        internal static string MongoRepository_DeleteAllError {
            get {
                return ResourceManager.GetString("MongoRepository_DeleteAllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al eliminar la entidad {0}.
        /// </summary>
        internal static string MongoRepository_DeleteError {
            get {
                return ResourceManager.GetString("MongoRepository_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al actualizar la entidad {0}.
        /// </summary>
        internal static string MongoRepository_UpdateError {
            get {
                return ResourceManager.GetString("MongoRepository_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo {0} ya existe y la configuracion no permite que sea reemplazado.
        /// </summary>
        internal static string SQLiteGenerator_DatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("SQLiteGenerator_DatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado al crear la fila {0} de tabla {1}.
        /// </summary>
        internal static string SQLiteGenerator_UnhandledRowError {
            get {
                return ResourceManager.GetString("SQLiteGenerator_UnhandledRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado al crear la tabla {0}.
        /// </summary>
        internal static string SQLiteGenerator_UnhandledTableError {
            get {
                return ResourceManager.GetString("SQLiteGenerator_UnhandledTableError", resourceCulture);
            }
        }
    }
}
